import type { Menu } from "../definations/Nav";
import {
  WebRounded,
  PlayLessonRounded,
  Inventory2Rounded,
  BuildRounded,
  ArticleRounded,
  EmailRounded,
  Recommend,
  Loyalty,
  NoteAlt,
  EmojiObjectsRounded,
  EmojiEmotionsRounded,
} from "@mui/icons-material";

const product: Menu = {
  id: 1,
  title: "Product Tools",
  icon: Inventory2Rounded,
  list: [
    {
      id: 1,
      category: "Product tool",
      title: "Product Descriptions",
      detail: "Generate attention-grabbing description for your product",
      endPoint: "productDescription",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
  ],
};

const digitalAdCopy: Menu = {
  id: 2,
  title: "Digital Ad Copy",
  icon: PlayLessonRounded,
  list: [
    {
      id: 1,
      category: "Digital Ad Copy tool",
      title: "Ad Copy Variants",
      detail: "BrainStrom variations to your ad copy.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 2,
      category: "Digital Ad Copy tool",
      title: "Facebook Headlines",
      detail: "Generate Facebook ad headlines for your business.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 3,
      category: "Digital Ad Copy tool",
      title: "Facebook Link Descriptions",
      detail: "Create a Facebook Link descriptions for your business.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 4,
      category: "Digital Ad Copy tool",
      title: "Facebook Listicle",
      detail: "Create a attention-grabbing list post for Facebook.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 5,
      category: "Digital Ad Copy tool",
      title: "Facebook Primary Text",
      detail: "Write A body Text for your Facebook.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 6,
      category: "Digital Ad Copy tool",
      title: "General Ad Copy",
      detail: "BrainStrom an outline for any type of ad.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 7,
      category: "Digital Ad Copy tool",
      title: "Google Description",
      detail: "Generate a description for your Google Ad.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 8,
      category: "Digital Ad Copy tool",
      title: "Google Headlines",
      detail: "Google ad headlines that helps you get catchy",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 9,
      category: "Digital Ad Copy tool",
      title: "LinkedIn Ad Copy",
      detail: "Generate Likedin Ad copy with ease",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
  ],
};

const statupTool: Menu = {
  id: 3,
  title: "Startup Tools",
  icon: BuildRounded,
  list: [
    {
      id: 1,
      category: "Startup tool",
      title: "Audience Refiner",
      detail: "Discover the right audience for your business.",
      toneRequired: false,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "Describe your audience",
      descriptionPlaceholder: "e.g. small business owners",
    },
    {
      id: 2,
      category: "Startup tool",
      title: "Brand Mission",
      detail: "Generate the perfect mission for your brand.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 3,
      category: "Startup tool",
      title: "Brand Voice",
      detail: "BrainStorm words for your brand",
      toneRequired: false,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 4,
      category: "Startup tool",
      title: "Motto Generator",
      detail: "Discover the perfect Motto for your business",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 5,
      category: "Startup tool",
      title: "Value Proposition",
      detail: "Find a perfect description for your company",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
  ],
};

const WebsiteCopy: Menu = {
  id: 4,
  title: "WebSite Copy",
  icon: WebRounded,
  list: [
    {
      id: 1,
      category: "WebSite Copy tool",
      title: "Call to Action",
      detail: "Generate right Call to action to your website",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 2,
      category: "WebSite Copy tool",
      title: "Event Copy",
      detail: "Generate a event promotion",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is the event?",
    },
    {
      id: 3,
      category: "WebSite Copy tool",
      title: "Landing Page Hero Text",
      detail: "Discover the best Landing Page Hero text on your website",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 4,
      category: "WebSite Copy tool",
      title: "Listicle",
      detail: "Generate sublist for specific topic to your website",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 5,
      category: "WebSite Copy tool",
      title: "Meta Descriptions",
      detail: "Create better meta description for your website.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 6,
      category: "WebSite Copy tool",
      title: "Microcopy",
      detail: "Humanze any text by applying microcopy.",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is the microcopy for?",
    },
    {
      id: 7,
      category: "WebSite Copy tool",
      title: "Question Generator",
      detail: "Generate engaging questions to your target audience.",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What are you generating questions for?",
      descriptionPlaceholder: "e.g. best email service",
    },
    {
      id: 8,
      category: "WebSite Copy tool",
      title: "Social Proof Text",
      detail: "Generate Perfect Social proof copy to your site.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 9,
      category: "WebSite Copy tool",
      title: "Subheader",
      detail: "Create a Subheader to your hero text.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 10,
      category: "WebSite Copy tool",
      title: "Testimonial Rewriter",
      detail: "Rewrite a testimonials to your website.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      descriptionName: "Your Testimonial",
      descriptionPlaceholder:
        "writy.ai is simple to use and saves my valuable time and resource!",
    },
  ],
};

const Blog: Menu = {
  id: 5,
  title: "Blog Tools",
  icon: ArticleRounded,
  list: [
    {
      id: 1,
      category: "Blog",
      title: "Blog Conclusion",
      detail: "Generate a conclusion to your blog article.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "What is your blog topic?",
      descriptionName: "What is the blog about?",
      brandPlaceholder: "e.g. The AI and future technoloagy",
      descriptionPlaceholder: "e.g. Ai is used in many domains in feature.",
    },
    {
      id: 2,
      category: "Blog tool",
      title: "Blog Ideas",
      detail: "Brainstrom topics for your blog articles.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 3,
      category: "Blog tool",
      title: "Blog Intro",
      detail: "Create the intro for a blog article.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "What is your blog title?",
      descriptionName: "What is the blog about?",
      brandPlaceholder:
        "e.g. 3 reasons to use AI powered Writy.ai copy writing tool",
      descriptionPlaceholder:
        "e.g. A blog about utilizing Writy.ai to save time and simplicity.",
    },
    {
      id: 4,
      category: "Blog tool",
      title: "Blog Outline",
      detail: "Outline your blog post or article.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "What is your blog title?",
      descriptionName: "What is the blog about?",
      brandPlaceholder:
        "e.g. 3 reasons to use AI powered Writy.ai copy writing tool",
      descriptionPlaceholder:
        "e.g. A blog about utilizing Writy.ai to save time and simplicity.",
    },
    {
      id: 5,
      category: "Blog tool",
      title: "Blog Title",
      detail: "Generate a great blog title for your blog or article post.",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "Describe your blog topic",
      descriptionPlaceholder:
        "e.g. a blog about the ai copy writing tool for small business",
    },
    {
      id: 6,
      category: "Blog tool",
      title: "Blog Title - Listicle",
      detail: "Perfect blog title for your listicle blog.",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "Describe your blog topic",
      descriptionPlaceholder:
        "e.g. a blog about the ai copy writing tool for small business",
    },
    {
      id: 7,
      category: "Blog tool",
      title: "Bullet Point to Blog Section",
      detail: "Generate an entire blog section based on main point.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "Blog Topic",
      descriptionName: "Write the main point of the paragraph?",
      brandPlaceholder: "e.g. How to use AI for small business",
      descriptionPlaceholder:
        "e.g. Marketing the product with ai based writy.ai copy writing tool.",
    },
    {
      id: 8,
      category: "Blog tool",
      title: "Freestyle",
      detail: "Generate anything you need to written.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "What are you looking to create?",
      descriptionName: "What are the main points you want to cover?",
      brandPlaceholder: "e.g. a sales email etc",
      descriptionPlaceholder:
        "e.g. Marketing the product with ai based writy.ai copy writing tool.",
    },
    {
      id: 9,
      category: "Blog tool",
      title: "Keyword Generator",
      detail: "Discover related keywords for your topic",
      toneRequired: false,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What topic are you posting about?",
      descriptionPlaceholder: "e.g. Life Hacks",
    },
  ],
};

const Email: Menu = {
  id: 6,
  title: "Email/Letter",
  icon: EmailRounded,
  list: [
    {
      id: 1,
      category: "Email/Letter tool",
      title: "Cancellation Email",
      detail: "Draft the perfect cancellation email.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 2,
      category: "Email/Letter tool",
      title: "Catchy Email Subject Lines",
      detail: "Draft the perfect email subject lines.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
    },
    {
      id: 3,
      category: "Email/Letter tool",
      title: "Confirmation Emails",
      detail: "Write a confirmation email template",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is the email for?",
      descriptionPlaceholder: "e.g. Signing up to a Email service",
    },
    {
      id: 4,
      category: "Email/Letter tool",
      title: "Follow Up Email",
      detail: "Draft a follow-up email after a meeting",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is the email for?",
      descriptionPlaceholder: "e.g. Signing up to a Email service",
    },
    {
      id: 5,
      category: "Email/Letter tool",
      title: "Thank You Note",
      detail: "Write a heartfelt thank you note.",
      toneRequired: true,
      brandNameRequired: true,
      descriptionRequired: true,
      brandName: "Who is the message for?",
      descriptionName: "What would you like to thank them for?",
      brandPlaceholder: "e.g. my friend",
      descriptionPlaceholder: "e.g. Joining me on this startup journey",
    },
    {
      id: 6,
      category: "Email/Letter tool",
      title: "Welcome Email",
      detail: "Generate a welcome email for new customers.",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is the email for?",
      descriptionPlaceholder: "e.g. Signing up to a Email service",
    },
  ],
};

const social: Menu = {
  id: 7,
  title: "Social Media Tools",
  icon: Recommend,
  list: [
    {
      id: 1,
      category: "Social Media tool",
      title: "Add Emoji To List",
      detail: "Find right emoji for any list",
      toneRequired: false,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "Write your list below",
      descriptionPlaceholder: `e.g.
        faster and cheep
        High quality
        Simple to use
      `,
    },
    {
      id: 2,
      category: "Social Media tool",
      title: "Bullet Points",
      detail: "Draft an outline for your any social media post",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
    },
    {
      id: 3,
      category: "Social Media tool",
      title: "Carousel Post",
      detail: "Generate carousel post for any Social media app",
      toneRequired: true,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is your topic?",
      descriptionPlaceholder: "e.g. Best ways to start a business",
    },
    {
      id: 4,
      category: "Social Media tool",
      title: "Crazy Youtube Ideas",
      detail: "Brainstorm crazy video ideas.",
      toneRequired: false,
      brandNameRequired: false,
      descriptionRequired: true,
    },
    {
      id: 5,
      category: "Social Media tool",
      title: "Hashtag Generator",
      detail: "Find a best hashtag to any post",
      toneRequired: false,
      brandNameRequired: false,
      descriptionRequired: true,
      descriptionName: "What is your post about",
    },
    {
      id: 6,
      category: "Social Media tool",
      title: "Hook Generator",
      detail: "Find a best hook to your youtube video",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
      descriptionName: "What is your topic?",
    },
    {
      id: 7,
      category: "Social Media tool",
      title: "Instagram Captions",
      detail: "Create Instagram captions for a photo",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
      descriptionName: "What is your post about?",
      descriptionPlaceholder: "e.g. video about how to solve any problem",
    },
    {
      id: 8,
      category: "Social Media tool",
      title: "Instagram Product Showcase",
      detail: "Create copy for showcasing your product on Instagram",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 9,
      category: "Social Media tool",
      title: "Keyword Generator",
      detail: "Generate keywords related to your post",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
      descriptionName: "What topic are you posting about?",
      descriptionPlaceholder: "e.g. Life Hacks",
    },
    {
      id: 10,
      category: "Social Media tool",
      title: "Launch Your Product",
      detail: "Find the right words to launch a product or event",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 11,
      category: "Social Media tool",
      title: "Relatable Experiences",
      detail:
        "Reach your audience with an experience they'll understand and relate to.",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: false,
      descriptionName: "What is your target niche",
      descriptionPlaceholder: "e.g. starting a new career",
    },
    {
      id: 12,
      category: "Social Media tool",
      title: "Short Text Hook",
      detail: "Brainstorm a short, powerful social media post",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 13,
      category: "Social Media tool",
      title: "TikTok Brainstorm Topics",
      detail: "BrainStorm topic for your TikTok videos",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: false,
      descriptionName: "What is your topic?",
      descriptionPlaceholder: "e.g. Easy ways to write content",
    },
    {
      id: 14,
      category: "Social Media tool",
      title: "Video Call To Action",
      detail: "Generate powerfull calls to action for any video.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
      brandName: "What is your video title?",
      descriptionName: "What is your video about?",
      brandPlaceholder: "e.g. How to start small business with no money",
      descriptionPlaceholder: "e.g. a video about how to start a business",
    },
    {
      id: 15,
      category: "Social Media tool",
      title: "YouTube Description Intro",
      detail: "Generate an engaging intro to get more views on YouTube.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
      brandName: "What is your video title?",
      descriptionName: "What is your video about?",
      brandPlaceholder: "e.g. How to start small business with no money",
      descriptionPlaceholder: "e.g. a video about how to start a business",
    },
    {
      id: 16,
      category: "Social Media tool",
      title: "YouTube Video Title",
      detail: "Generate the best title for your vidos.",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
      descriptionName: "What is your video about?",
      brandPlaceholder: "e.g. How to start small business with no money",
      descriptionPlaceholder: "e.g. a video about how to start a business",
    },
  ],
};
const sales: Menu = {
  id: 1,
  title: "Sales Tools",
  icon: Loyalty,
  list: [
    {
      id: 1,
      category: "Sales Tool",
      title: "Attention-Interest-Desire-Action",
      detail: "Write a compelling ad, social media post, or email",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 2,
      category: "Sales Tool",
      title: "Before-After-Bridge",
      detail:
        "Write Before-After-Bridge copy for emails, ad campaign, and social media posts.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 3,
      category: "Sales Tool",
      title: "Feature to Benefits",
      detail: "Extract the product's benefits from a list of the features.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 4,
      category: "Sales Tool",
      title: "Feature-Advantage-Benefit",
      detail: "Write an ad that highlights your unique selling point.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 5,
      category: "Sales Tool",
      title: "Marketing Angles",
      detail: "Find new angles for your marketing.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 6,
      category: "Sales Tool",
      title: "Pain-Agitate-Solution",
      detail: "Rewrite text to address a specific customer pain point.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 7,
      category: "Sales Tool",
      title: "Problem-Promise-Proof-Proposal",
      detail:
        "Draft a proposal that follows the Problem-Promise-Proof Proposal format.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
    {
      id: 8,
      category: "Sales Tool",
      title: "QUEST Copywriting",
      detail: "Draft a brief outline for an ad, email, or social media post",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
    },
  ],
};

const writingTools: Menu = {
  id: 1,
  title: "Writing Tools",
  icon: NoteAlt,
  list: [
    {
      id: 1,
      category: "Writing Tool",
      title: "Adjective Accelerator",
      detail: "Find stronger alternatives for any adjective.",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: false,
      descriptionName: "Describe your adjective",
      descriptionPlaceholder: "e.g. simpler",
    },
    {
      id: 2,
      category: "Writing Tool",
      title: "Analogy Generator",
      detail: "Find relatable analogies for any topic.",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: false,
      descriptionName: "List a topic or two!",
      descriptionPlaceholder: "e.g. Startups and surfing",
    },
    {
      id: 3,
      category: "Writing Tool",
      title: "Bullet Point to Blog Section",
      detail: "Generate an entire blog section based on a single bullet point.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
      brandName: "Blog Topic",
      descriptionName: "What is the main point of the paragraph?",
      brandPlaceholder: "e.g. How to use AI in daily life",
      descriptionPlaceholder:
        "e.g. Ai can be used to track and manage the health.",
    },
    {
      id: 4,
      category: "Writing Tool",
      title: "Bullet Point to Paragraph",
      detail: "Convert a bullet point outline into a full paragraph.",
      brandNameRequired: true,
      descriptionRequired: true,
      toneRequired: true,
      brandName: "Essay Topic",
      descriptionName: "What is the main point of the paragraph?",
      brandPlaceholder: "e.g. How to use AI in daily life",
      descriptionPlaceholder:
        "e.g. Ai can be used to track and manage the health.",
    },
    {
      id: 5,
      category: "Writing Tool",
      title: "Cliffhanger",
      detail: "Add a cliffhanger to your paragraph.",
      brandNameRequired: false,
      descriptionRequired: true,
      toneRequired: true,
      descriptionName: "What is your topic?",
    },
    {
      id: 6,
      category: "Writing Tool",
      title: "Essay Intro",
    },
    {
      id: 7,
      category: "Writing Tool",
      title: "Essay Outline",
    },
    {
      id: 8,
      category: "Writing Tool",
      title: "Explain Like I'm 5",
    },
    {
      id: 9,
      category: "Writing Tool",
      title: "Freestyle",
    },
    {
      id: 10,
      category: "Writing Tool",
      title: "Hero Story Intro",
    },
    {
      id: 11,
      category: "Writing Tool",
      title: "Hero Story Villain",
    },
    {
      id: 12,
      category: "Writing Tool",
      title: "Passive To Active Voice",
    },
    {
      id: 14,
      category: "Writing Tool",
      title: "Press Release Intros",
    },
    {
      id: 15,
      category: "Writing Tool",
      title: "Rewrite With Keywords",
    },
    {
      id: 16,
      category: "Writing Tool",
      title: "Sentence Rewriter",
    },
    {
      id: 17,
      category: "Writing Tool",
      title: "Simplify Sentences",
    },
    {
      id: 18,
      category: "Writing Tool",
      title: "Tone Changer",
    },
    {
      id: 19,
      category: "Writing Tool",
      title: "Two Sentence Stories",
    },
    {
      id: 20,
      category: "Writing Tool",
      title: "Verb Booster",
    },
  ],
};

const Brainstorming: Menu = {
  id: 1,
  title: "Brainstorming Tools",
  icon: EmojiObjectsRounded,
  list: [
    {
      id: 1,
      category: "Brainstorming Tool",
      title: "Growth Ideas",
    },
    {
      id: 2,
      category: "Brainstorming Tool",
      title: "Name Generator",
    },
    {
      id: 3,
      category: "Brainstorming Tool",
      title: "Next Product",
    },
    {
      id: 4,
      category: "Brainstorming Tool",
      title: "Startup Ideas",
    },
    {
      id: 5,
      category: "Brainstorming Tool",
      title: "Viral Ideas",
    },
  ],
};

const PersonalTools: Menu = {
  id: 1,
  title: "Personal Tools",
  icon: EmojiEmotionsRounded,
  list: [
    {
      id: 1,
      category: "Personal tool",
      title: "Birthday Card",
    },
    {
      id: 2,
      category: "Personal tool",
      title: "Clubhouse Bio",
    },
    {
      id: 3,
      category: "Personal tool",
      title: "Cover Letter",
    },
    {
      id: 4,
      category: "Personal tool",
      title: "Love Letter",
    },
    {
      id: 5,
      category: "Personal tool",
      title: "Resume Bullet Points",
    },
  ],
};

export const tools: Menu[] = [
  product,
  social,
  statupTool,
  // writingTools,
  digitalAdCopy,
  WebsiteCopy,
  Blog,
  Email,
  sales,
  // Brainstorming,
  // PersonalTools,
];

export const searchTools: { id: number; title: string; category: string }[] = [
  ...product.list,
  ...social.list,
  ...statupTool.list,
  // ...writingTools.list,
  ...digitalAdCopy.list,
  ...WebsiteCopy.list,
  ...Blog.list,
  ...Email.list,
  ...sales.list,
  // ...Brainstorming.list,
  // ...PersonalTools.list,
];
