const theme = {
  palette: {
    primary: {
      main: "#005249",
      light: "#5BE584",
      lighter: "#C8FACD",
      dark: "#007B55",
      darker: "#005249",
    },
    secondary: {
      main: "#3366FF",
      light: "#84A9FF",
      lighter: "#D6E4FF",
      dark: "#1939B7",
      darker: "#091A7A",
    },
    info: {
      main: "#00B8D9",
      light: "#61F3F3",
      lighter: "#CAFDF5",
      dark: "#006C9C",
      darker: "#003768",
    },
    success: {
      main: "#36B37E",
      light: "#86E8AB",
      lighter: "#D8FBDE",
      dark: "#1B806A",
      darker: "#0A5554",
    },
    warning: {
      main: "#FFAB00",
      light: "#FFD666",
      lighter: "#FFF5CC",
      dark: "#B76E00",
      darker: "#7A4100",
    },
    error: {
      main: "#FF5630",
      light: "#FFAC82",
      lighter: "#FFE9D5",
      dark: "#B71D18",
      darker: "#7A0916",
    },
    grey: {
      100: "#F9FAFB",
      200: "#F4F6F8",
      300: "#DFE3E8",
      400: "#C4CDD5",
      500: "#919EAB",
      600: "#637381",
      700: "#454F5B",
      800: "#212B36",
      900: "#161C24",
    },
  },
  typography: {
    fontFamily: "Public Sans",
    fontSize: "16px",
    h1: {
      fontFamily: "Public Sans",
      fontSize: "64px",
      fontWeight: 800,
      lineHeight: "80px",
      letterSpacing: "0px",
      textAlign: "left",
    },
    h2: {
      fontFamily: "Public Sans",
      fontSize: "48px",
      fontWeight: 800,
      lineHeight: "64px",
      letterSpacing: "0px",
      textAlign: "left",
    },
    h3: {
      fontFamily: "Public Sans",
      fontSize: "32px",
      fontWeight: 700,
      lineHeight: "48px",
      letterSpacing: "0px",
      textAlign: "left",
    },
    h4: {
      fontFamily: "Public Sans",
      fontSize: "24px",
      fontWeight: 700,
      lineHeight: "36px",
      letterSpacing: "0px",
      textAlign: "left",
    },
    h5: {
      fontFamily: "Public Sans",
      fontSize: "20px",
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0px",
      textAlign: "left",
    },
    h6: {
      fontFamily: "Public Sans",
      fontSize: "18px",
      fontWeight: 700,
      lineHeight: "28px",
      letterSpacing: "0px",
      textAlign: "left",
    },
  },
};

export default theme;
